title: "Darryl's Pixels"
author: "Darryl Gouder"
description: "Blog about code and stuff..."
more: "read more »"
url: "https://dargouder.github.io/darryls-pixels"
baseurl: "/darryls-pixels"
paginate: 2
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: false
  dark: false

navigation:
  - index.html
  - archive.html
  - about.md

comments:
  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"
disqus:
  shortname: darryls-pixels
  
links: # see http://fontawesome.io/icons/#brand for all possible icons
  - twitter: "https://twitter.com/dargouder"
  - github: "https://github.com/dargouder"
  - envelope: "mailto:dargouder@gmail.com"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate]
